services:
  docs-validator:
    build:
      context: ../
      dockerfile: docs-validate/Dockerfile
    image: redis-memory-docs-validate:latest
    working_dir: /workspace
    volumes:
      - ..:/workspace
    command: ./docs-validate/validate-docs.sh
